import { tool } from '@opencode-ai/plugin';

/**
 * OpenCode CoDesign Plugin
 * Provides design generation tools following Open CoDesign methodology
 */

export const id = 'codesign';

export async function server(input, options = {}) {
  const { client, project, directory, worktree, $ } = input;

  // Design templates registry
  const TEMPLATES = {
    'minimal-landing': {
      name: 'Minimal Landing Page',
      description: 'Clean, minimal landing page with hero section',
      direction: 'minimal',
    },
    'bold-campaign': {
      name: 'Bold Campaign Page',
      description: 'High-impact campaign page with bold visuals',
      direction: 'bold',
    },
    'dense-dashboard': {
      name: 'Dense Dashboard',
      description: 'Information-dense dashboard layout',
      direction: 'dense',
    },
    'marketing-saas': {
      name: 'SaaS Marketing Page',
      description: 'Full-featured SaaS marketing page',
      direction: 'minimal',
    },
  };

  // Design tokens presets
  const TOKEN_PRESETS = {
    minimal: {
      colors: {
        primary: '#2563eb',
        primaryDark: '#1d4ed8',
        background: '#ffffff',
        surface: '#f8fafc',
        text: '#0f172a',
        textMuted: '#64748b',
        border: '#e2e8f0',
      },
      fonts: {
        sans: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      },
    },
    bold: {
      colors: {
        primary: '#dc2626',
        primaryDark: '#b91c1c',
        background: '#0f172a',
        surface: '#1e293b',
        text: '#f8fafc',
        textMuted: '#94a3b8',
        border: '#334155',
      },
      fonts: {
        sans: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      },
    },
    dense: {
      colors: {
        primary: '#059669',
        primaryDark: '#047857',
        background: '#ffffff',
        surface: '#f9fafb',
        text: '#111827',
        textMuted: '#6b7280',
        border: '#e5e7eb',
      },
      fonts: {
        sans: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      },
    },
  };

  // Helper functions
  async function generateAppFromTemplate(template, name, tokens) {
    return `function App() {
  const tokens = ${JSON.stringify(tokens, null, 2)};

  // ${TEMPLATES[template].name}
  // Generated by OpenCode CoDesign

  return (
    <div style={{ fontFamily: tokens.fonts.sans, color: tokens.colors.text }}>
      <header>
        <h1>${name}</h1>
      </header>
      <main>
        <p>Your ${TEMPLATES[template].name} starts here.</p>
      </main>
    </div>
  );
}

export default App;
`;
  }

  async function generateDesignDoc(template, name, tokens) {
    return `# ${name} - Design System

Template: ${TEMPLATES[template].name}
Direction: ${TEMPLATES[template].direction}

## Design Tokens

\`\`\`json
${JSON.stringify(tokens, null, 2)}
\`\`\`

## Usage

This design follows the Open CoDesign methodology with a focus on:
- Clear visual direction
- Consistent design tokens
- Semantic HTML
- Accessibility
- Real content (no lorem ipsum)

## Next Steps

1. Customize the design tokens above
2. Implement your components using these tokens
3. Run the "check" tool to validate quality
4. Use the "preview" tool to see it in action
`;
  }

  // Return hooks
  return {
    tool: {
      // Scaffold tool
      scaffold: tool({
        description: 'Scaffold a new design from an Open CoDesign template. Creates App.jsx with design tokens and DESIGN.md with design system documentation. Use when user wants to create a design with documented design system.',
        args: {
          template: tool.schema.enum(['minimal-landing', 'bold-campaign', 'dense-dashboard', 'marketing-saas']).describe('Template name'),
          name: tool.schema.string().describe('Project name'),
          outputDir: tool.schema.string().optional().describe('Output directory (default: current directory)'),
        },
        async execute(args, context) {
          const { template, name, outputDir = '.' } = args;
          const templateInfo = TEMPLATES[template];

          if (!templateInfo) {
            throw new Error(`Template not found: ${template}`);
          }

          const tokens = TOKEN_PRESETS[templateInfo.direction];
          const outputPath = `${outputDir}/${name}`;

          // Create output directory
          await $`mkdir -p ${outputPath}`;

          // Generate App.jsx
          const appContent = await generateAppFromTemplate(template, name, tokens);
          await Bun.write(`${outputPath}/App.jsx`, appContent);

          // Generate DESIGN.md
          const designDoc = await generateDesignDoc(template, name, tokens);
          await Bun.write(`${outputPath}/DESIGN.md`, designDoc);

          return {
            output: `✅ Scaffolded "${templateInfo.name}" in ${outputPath}\n\nFiles created:\n- App.jsx\n- DESIGN.md\n\nNext steps:\n1. Review the design system in DESIGN.md\n2. Customize the design tokens\n3. Run the preview tool to see it in action`,
            metadata: {
              template,
              outputPath,
              files: ['App.jsx', 'DESIGN.md'],
            },
          };
        },
      }),

      // Preview tool
      preview: tool({
        description: 'Generate a preview URL for the design',
        args: {
          file: tool.schema.string().describe('Path to App.jsx file'),
        },
        async execute(args, context) {
          const { file } = args;
          const content = await Bun.file(file).text();
          const hasReactDOM = content.includes('ReactDOM.createRoot');

          return `📱 Preview Instructions:\n\n1. Install dependencies:\n   npm install react react-dom\n\n2. Create index.html:\n   <!DOCTYPE html>\n   <html>\n     <head><title>Preview</title></head>\n     <body><div id="root"></div></body>\n   </html>\n\n3. ${hasReactDOM ? 'File is ready!' : 'Add ReactDOM.createRoot to your App.jsx'}\n\n4. Use a dev server:\n   npx vite\n   # or\n   npx serve\n\nFile analyzed: ${file}`;
        },
      }),

      // Check tool
      check: tool({
        description: 'Check design quality and accessibility of an Open CoDesign generated file. Validates design tokens, semantic HTML, accessibility, responsive design, and real content. Use when user wants to validate a design.',
        args: {
          file: tool.schema.string().describe('Path to App.jsx file'),
        },
        async execute(args, context) {
          const { file } = args;
          const content = await Bun.file(file).text();

          const checks = {
            hasTokens: content.includes('const tokens'),
            hasSemanticHTML: /(<header|<nav|<main|<section|<footer)/.test(content),
            hasAccessibility: /aria-|role=/.test(content) || content.includes('alt='),
            hasResponsive: /clamp\(|auto-fit|@media/.test(content),
            noLoremIpsum: !content.toLowerCase().includes('lorem ipsum'),
          };

          const score = Object.values(checks).filter(Boolean).length;
          const total = Object.keys(checks).length;
          const percentage = Math.round((score / total) * 100);

          let report = `🔍 Design Quality Check\n\n`;
          report += `Score: ${score}/${total} (${percentage}%)\n\n`;
          report += `${checks.hasTokens ? '✅' : '❌'} Design tokens\n`;
          report += `${checks.hasSemanticHTML ? '✅' : '❌'} Semantic HTML\n`;
          report += `${checks.hasAccessibility ? '✅' : '❌'} Accessibility\n`;
          report += `${checks.hasResponsive ? '✅' : '❌'} Responsive design\n`;
          report += `${checks.noLoremIpsum ? '✅' : '❌'} Real content\n\n`;

          if (percentage >= 80) {
            report += `🎉 Excellent! Your design meets production quality standards.`;
          } else if (percentage >= 60) {
            report += `👍 Good! Consider improving the areas marked as ❌.`;
          } else {
            report += `⚠️  Needs improvement. Review the Open CoDesign methodology.`;
          }

          return {
            output: report,
            metadata: {
              score,
              total,
              percentage,
              checks,
            },
          };
        },
      }),

      // Tokens tool
      tokens: tool({
        description: 'Get Open CoDesign design tokens (colors, fonts, spacing, etc.) for a specific visual direction (minimal, bold, dense). Use when user asks about design tokens or color schemes.',
        args: {
          direction: tool.schema.enum(['minimal', 'bold', 'dense']).describe('Visual direction'),
        },
        async execute(args, context) {
          const { direction } = args;
          const tokens = TOKEN_PRESETS[direction];

          return `🎨 Design Tokens for "${direction}" direction:\n\n${JSON.stringify(tokens, null, 2)}\n\nUse these tokens in your design to maintain consistency.`;
        },
      }),

      // List templates tool
      'list-templates': tool({
        description: 'List all available Open CoDesign templates (minimal-landing, bold-campaign, dense-dashboard, marketing-saas). Use when user asks about available templates or wants to see template options.',
        args: {},
        async execute(args, context) {
          let output = '📚 Available Design Templates:\n\n';

          for (const [key, template] of Object.entries(TEMPLATES)) {
            output += `• ${key}\n`;
            output += `  ${template.name}\n`;
            output += `  ${template.description}\n`;
            output += `  Direction: ${template.direction}\n\n`;
          }

          output += 'Use the "scaffold" tool to create a new design from a template.';

          return output;
        },
      }),
    },

    // Event hook for logging
    async event({ event }) {
      if (event.type === 'tool.execute' && event.tool.startsWith('codesign.')) {
        console.log(`[CoDesign] Tool executed: ${event.tool}`);
      }
    },
  };
}
